#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Rutas David


#PODCASTS
podcasts:
  path: /podcasts
  controller: App\Controller\PodcastController::podcasts
  methods: GET|POST


podcastById:
  path: /podcast/{id}
  controller: App\Controller\PodcastController::podcastById
  methods: GET


podcastsbyUser:
  path: /usuario/{id}/podcasts
  controller: App\Controller\PodcastController::podcastsByUser
  methods: GET


#podcastsSeguimientos:
  #path: /usuario/{userId}/podcast/{podcastId}
  #controller: App\Controller\PodcastController::podcastsSeguimientos
  #methods: POST|DELETE


#CAPÍTULOS
capitulosByPodcast:
  path: /podcast/{id}/capitulos
  controller: App\Controller\CapituloController::capitulosByPodcast
  methods: GET


capitulosById:
  path: /podcast/{podcastId}/capitulo/{capituloId}
  controller: App\Controller\CapituloController::capitulosById
  methods: GET


#CANCIONES
canciones:
  path: /canciones
  controller: App\Controller\CancionController::canciones
  methods: GET


cancionesById:
  path: /canciones/{id}
  controller: App\Controller\CancionController::cancionesById
  methods: GET


cancionesByPlaylist:
  path: /playlist/{id}/canciones
  controller: App\Controller\CancionController::cancionesByPlaylist
  methods: GET


modiCancionesById:
  path: /playlist/{playlistId}/cancion/{cancionId}
  controller: App\Controller\CancionController::modiCancionesById
  methods: POST|DELETE


#ARTISTAS
artistas:
  path: /artistas
  controller: App\Controller\ArtistaController::artistas
  methods: GET


artistasAlbums:
  path: /artista/{id}/albums
  controller: App\Controller\ArtistaController::artistasAlbums
  methods: GET

  
artistasAlbumsByIds:
  path: /artista/{artistaId}/album/{albumId}
  controller: App\Controller\ArtistaController::artistasAlbumsByIds
  methods: GET


#TIPOS DE DESCARGA
tiposDescargas:
  path: /tiposdescargas
  controller: App\Controller\TipoDescargaController::tiposDescargas
  methods: GET








#Rutas Álvaro


#USUARIOS
usuarios:
  path: /usuarios #Hecho
  controller: App\Controller\UsuarioController::usuarios
  methods: GET|POST


usuarioById: #Hecho
  path: /usuario/{id}
  controller: App\Controller\UsuarioController::usuarioById
  methods: GET|PUT|DELETE


usuarioSeguidos: #Hecho
  path: /usuario/{id}/seguidos
  controller: App\Controller\UsuarioController::usuarioSeguidos
  methods: GET


#usuarioSigueUsuario: 
#  path: /usuario/{usuario_id}/sigue/{usuario_seguido_id}
#  controller: App\Controller\UsuarioController::usuarioSigueUsuario
#  methods: POST|DELETE


configuracionByUsuario: #Hecho
  path: /usuarios/{usuario_id}/configuracion
  controller: App\Controller\ConfiguracionController::configuracionByUsuario
  methods: GET|PUT


#SUSCRIPCIONES
suscripciones: #Hecho
  path: /usuario/{id}/suscripciones
  controller: App\Controller\SuscripcionController::suscripciones
  methods: GET


suscripcionesById: #Hecho
  path: /usuario/{usuarioId}/suscripcion/{suscripcionId}
  controller: App\Controller\SuscripcionController::suscripcionesById
  methods: GET


#PLAYLISTS
playlists: #Hecho
  path: /playlists
  controller: App\Controller\PlaylistController::playlists
  methods: GET|POST


playlistsById: #Hecho
  path: /playlist/{id}
  controller: App\Controller\PlaylistController::playlistsById
  methods: GET


playlistsByUsuario: #Hecho
  path: /usuario/{id}/playlists
  controller: App\Controller\UsuarioController::playlistsByUsuario
  methods: GET


playlistsByUsuarioId:
  path: /usuario/{usuarioId}/playlist/{playlistId}
  controller: App\Controller\UsuarioController::playlistsByUsuarioId
  methods: GET|PUT|DELETE


#ALBUMS
albums: #Hecho
  path: /albums
  controller: App\Controller\AlbumController::albums
  methods: GET


albumById: #Hecho
  path: /album/{id}
  controller: App\Controller\AlbumController::albumsById
  methods: GET


albumsAndCanciones: #Hecho
  path: /album/{id}/canciones
  controller: App\Controller\AlbumController::albumsAndCanciones
  methods: GET


#CALIDAD
calidades: #Hecho
  path: /calidades
  controller: App\Controller\CalidadController::calidades
  methods: GET


#IDIOMA
idiomas: #Hecho
  path: /idiomas
  controller: App\Controller\IdiomaController::idiomas
  methods: GET
